name: FallCreek
favicon: null
layout_spectrum: 0.83934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7cdc9'
    - '#f2f2f2'
    - '#3f4523'
    - '#6f684c'
    - '#938c6f'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: shares
    item: null
    url: null
